---
- name: 给用户绑定权限
  ignore_errors: yes
  shell:  kubectl create clusterrolebinding cluster-system-anonymous --clusterrole=cluster-admin --user=system:anonymous


- name: 制作config文件
  ignore_errors: yes
  shell: kubectl config set-cluster  kubernetes     --kubeconfig=/root/test.conf --embed-certs=true --certificate-authority={{ k8s_work_dir }}/ssl/ca.pem   --server="https://{{ masterip }}:6443" && \
         kubectl config  set-credentials kubernetes-admin      --client-certificate=/root/Ansible-K8S/ssl/k8s/admin.pem  --client-key=/root/Ansible-K8S-master/ssl/k8s/admin-key.pem   --embed-certs=true   --kubeconfig=/root/test.conf  && \
          kubectl config set-context kubernetes-admin@kubernetes   --cluster=kubernetes   --user=kubernetes-admin --kubeconfig=/root/test.conf   && \
          cp /root/test.conf   /root/.kube/config   

